import { createFileRoute, Link } from '@tanstack/react-router';
import { useState } from 'react';
import { statisticsRequest } from '@/lib/app-statistics';
export const Route=createFileRoute('/statistics')({head:()=>({meta:[{title:'Statistiche private — Safe Scan Eats'},{name:'robots',content:'noindex,nofollow'}]}),component:Statistics});
type Report={browsers:number;active7:number;active30:number;standalone:number;eligible7:number;returned7:number;eligible30:number;returned30:number;sources:Record<string,number>;features:Record<string,number>;ratings:Record<string,number>;reasons:Record<string,number>;daily:{day:string;browsers:number}[];generatedAt:string};
function Statistics(){
 const [password,setPassword]=useState('');const [report,setReport]=useState<Report|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError('');try{setReport(await statisticsRequest({action:'report'},password));}catch(e){setReport(null);setError(e instanceof Error?e.message:'Errore');}finally{setBusy(false);}}
 const rate=(n:number,d:number)=>d?`${n} su ${d} (${Math.round(n/d*100)}%)`:'In attesa: campione non ancora maturo';
 const group=(title:string,values:Record<string,number>,labels:Record<string,string>)=><section className="rounded-2xl border bg-white p-5"><h2 className="mb-3 text-xl font-bold">{title}</h2>{Object.keys(values).length?<dl>{Object.entries(values).map(([key,value])=><div key={key} className="flex justify-between border-b py-2"><dt>{labels[key]??key}</dt><dd className="font-bold">{value}</dd></div>)}</dl>:<p>Nessun dato raccolto.</p>}</section>;
 return <main className="mx-auto max-w-3xl space-y-5 p-5"><Link to="/" className="underline">Torna all’app</Link><h1 className="text-3xl font-black">Statistiche private</h1>
 <form onSubmit={e=>{e.preventDefault();void load();}} className="space-y-3 rounded-2xl border bg-white p-5"><label className="block font-bold">Password del gestore<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 block w-full rounded-xl border p-3" required/></label><button className="rounded-xl bg-primary px-5 py-3 font-bold text-white" disabled={busy}>{busy?'Caricamento…':report?'Aggiorna':'Accedi'}</button>{report&&<button className="ml-3 underline" type="button" onClick={()=>{setPassword('');setReport(null);}}>Esci</button>}<p role="alert">{error}</p></form>
 {report&&<><p className="text-sm">Aggiornato: {new Date(report.generatedAt).toLocaleString('it-IT')}. Dati degli ultimi 180 giorni, solo browser che hanno acconsentito. Un browser può rappresentare più persone e una persona più browser. Gli accessi precedenti all’attivazione non sono recuperabili.</p>
 <div className="grid grid-cols-2 gap-3">{[['Browser rilevati',report.browsers],['Attivi negli ultimi 7 giorni',report.active7],['Attivi negli ultimi 30 giorni',report.active30],['Uso dalla Home / installazione rilevata',report.standalone]].map(([label,n])=><section key={String(label)} className="rounded-2xl border bg-white p-5"><p className="text-sm">{label}</p><p className="mt-2 text-3xl font-black">{n}</p></section>)}</div>
 <section className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Tornano a usare l’app?</h2><p>Seconda settimana: <strong>{rate(report.returned7,report.eligible7)}</strong></p><p>Dopo un mese: <strong>{rate(report.returned30,report.eligible30)}</strong></p><p className="text-sm">Ritorno tra i giorni 7–13 e 30–36 dalla prima visita. Il calcolo include solo browser che hanno completato tutta la finestra. Mancato ritorno non significa disinstallazione o insoddisfazione.</p></section>
 {group('Da dove arrivano',report.sources,{facebook:'Facebook',instagram:'Instagram',tiktok:'TikTok',direct:'Diretti / altra provenienza'})}
 {group('Sezioni aperte: browser distinti',report.features,{open:'Apertura',scan:'Scanner',recipes:'Ricette',shopping:'Lista della spesa',search:'Ricerca',installed:'Uso dalla Home / installazione rilevata'})}
 {group('Giudizi volontari',report.ratings,{useful:'Utile',improve:'Utile, da migliorare',not_useful:'Non utile'})}
 {group('Cosa migliorare',report.reasons,{products:'Prodotti mancanti',recipes:'Ricette',difficult:'Difficile da usare',other:'Altro'})}
 <section className="rounded-2xl border bg-white p-5"><h2 className="mb-3 text-xl font-bold">Accessi giornalieri</h2><table className="w-full text-left"><thead><tr><th scope="col">Giorno (UTC)</th><th scope="col">Browser</th></tr></thead><tbody>{report.daily.map(row=><tr key={row.day}><td className="py-2">{row.day}</td><td>{row.browsers}</td></tr>)}</tbody></table></section>
 <section className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Link per i social</h2>{['facebook','instagram','tiktok'].map(source=><div key={source}><label className="capitalize">{source}<input readOnly onFocus={e=>e.target.select()} className="mt-1 w-full rounded-lg border p-2 text-sm" value={`https://safe-scan-eats.vercel.app/?utm_source=${source}`}/></label></div>)}<p className="text-sm">Usa il link corrispondente nel profilo o nella pubblicità. Il link dentro un video resta un’immagine.</p></section>
 </>}
 </main>;
}
