/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as CrsRouteImport } from './routes/crs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as ProductCodeRouteImport } from './routes/product.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const CrsRoute = CrsRouteImport.update({
  id: '/crs',
  path: '/crs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCodeRoute = ProductCodeRouteImport.update({
  id: '/product/$code',
  path: '/product/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/crs': typeof CrsRoute
  '/history': typeof HistoryRoute
  '/ingredients': typeof IngredientsRoute
  '/recipes': typeof RecipesRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/shopping': typeof ShoppingRoute
  '/statistics': typeof StatisticsRoute
  '/stores': typeof StoresRoute
  '/product/$code': typeof ProductCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/crs': typeof CrsRoute
  '/history': typeof HistoryRoute
  '/ingredients': typeof IngredientsRoute
  '/recipes': typeof RecipesRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/shopping': typeof ShoppingRoute
  '/statistics': typeof StatisticsRoute
  '/stores': typeof StoresRoute
  '/product/$code': typeof ProductCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/crs': typeof CrsRoute
  '/history': typeof HistoryRoute
  '/ingredients': typeof IngredientsRoute
  '/recipes': typeof RecipesRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/shopping': typeof ShoppingRoute
  '/statistics': typeof StatisticsRoute
  '/stores': typeof StoresRoute
  '/product/$code': typeof ProductCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/crs'
    | '/history'
    | '/ingredients'
    | '/recipes'
    | '/scan'
    | '/search'
    | '/shopping'
    | '/statistics'
    | '/stores'
    | '/product/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/crs'
    | '/history'
    | '/ingredients'
    | '/recipes'
    | '/scan'
    | '/search'
    | '/shopping'
    | '/statistics'
    | '/stores'
    | '/product/$code'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/crs'
    | '/history'
    | '/ingredients'
    | '/recipes'
    | '/scan'
    | '/search'
    | '/shopping'
    | '/statistics'
    | '/stores'
    | '/product/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  CrsRoute: typeof CrsRoute
  HistoryRoute: typeof HistoryRoute
  IngredientsRoute: typeof IngredientsRoute
  RecipesRoute: typeof RecipesRoute
  ScanRoute: typeof ScanRoute
  SearchRoute: typeof SearchRoute
  ShoppingRoute: typeof ShoppingRoute
  StatisticsRoute: typeof StatisticsRoute
  StoresRoute: typeof StoresRoute
  ProductCodeRoute: typeof ProductCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crs': {
      id: '/crs'
      path: '/crs'
      fullPath: '/crs'
      preLoaderRoute: typeof CrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$code': {
      id: '/product/$code'
      path: '/product/$code'
      fullPath: '/product/$code'
      preLoaderRoute: typeof ProductCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  CrsRoute: CrsRoute,
  HistoryRoute: HistoryRoute,
  IngredientsRoute: IngredientsRoute,
  RecipesRoute: RecipesRoute,
  ScanRoute: ScanRoute,
  SearchRoute: SearchRoute,
  ShoppingRoute: ShoppingRoute,
  StatisticsRoute: StatisticsRoute,
  StoresRoute: StoresRoute,
  ProductCodeRoute: ProductCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
