/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProductCodeRouteImport } from './routes/product.$code'
import { Route as ShoppingRouteImport } from './routes/shopping'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AnalysisRoute = AnalysisRouteImport.update({ id: '/analysis', path: '/analysis', getParentRoute: () => rootRouteImport } as any)
const HistoryRoute = HistoryRouteImport.update({ id: '/history', path: '/history', getParentRoute: () => rootRouteImport } as any)
const IngredientsRoute = IngredientsRouteImport.update({ id: '/ingredients', path: '/ingredients', getParentRoute: () => rootRouteImport } as any)
const ScanRoute = ScanRouteImport.update({ id: '/scan', path: '/scan', getParentRoute: () => rootRouteImport } as any)
const SearchRoute = SearchRouteImport.update({ id: '/search', path: '/search', getParentRoute: () => rootRouteImport } as any)
const ProductCodeRoute = ProductCodeRouteImport.update({ id: '/product/$code', path: '/product/$code', getParentRoute: () => rootRouteImport } as any)
const ShoppingRoute = ShoppingRouteImport.update({ id: '/shopping', path: '/shopping', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/history': typeof HistoryRoute
  '/ingredients': typeof IngredientsRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/product/$code': typeof ProductCodeRoute
  '/shopping': typeof ShoppingRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/history': typeof HistoryRoute
  '/ingredients': typeof IngredientsRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/product/$code': typeof ProductCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analysis' | '/history' | '/ingredients' | '/scan' | '/search' | '/product/$code' | '/shopping'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analysis' | '/history' | '/ingredients' | '/scan' | '/search' | '/product/$code' | '/shopping'
  id: '__root__' | '/' | '/analysis' | '/history' | '/ingredients' | '/scan' | '/search' | '/product/$code' | '/shopping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  HistoryRoute: typeof HistoryRoute
  IngredientsRoute: typeof IngredientsRoute
  ScanRoute: typeof ScanRoute
  SearchRoute: typeof SearchRoute
  ProductCodeRoute: typeof ProductCodeRoute
  ShoppingRoute: typeof ShoppingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/analysis': { id: '/analysis'; path: '/analysis'; fullPath: '/analysis'; preLoaderRoute: typeof AnalysisRouteImport; parentRoute: typeof rootRouteImport }
    '/history': { id: '/history'; path: '/history'; fullPath: '/history'; preLoaderRoute: typeof HistoryRouteImport; parentRoute: typeof rootRouteImport }
    '/ingredients': { id: '/ingredients'; path: '/ingredients'; fullPath: '/ingredients'; preLoaderRoute: typeof IngredientsRouteImport; parentRoute: typeof rootRouteImport }
    '/scan': { id: '/scan'; path: '/scan'; fullPath: '/scan'; preLoaderRoute: typeof ScanRouteImport; parentRoute: typeof rootRouteImport }
    '/search': { id: '/search'; path: '/search'; fullPath: '/search'; preLoaderRoute: typeof SearchRouteImport; parentRoute: typeof rootRouteImport }
    '/product/$code': { id: '/product/$code'; path: '/product/$code'; fullPath: '/product/$code'; preLoaderRoute: typeof ProductCodeRouteImport; parentRoute: typeof rootRouteImport }
    '/shopping': { id: '/shopping'; path: '/shopping'; fullPath: '/shopping'; preLoaderRoute: typeof ShoppingRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AnalysisRoute,
  HistoryRoute,
  IngredientsRoute,
  ScanRoute,
  SearchRoute,
  ProductCodeRoute,
  ShoppingRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}